import urllib.request
import urllib.parse
import urllib.error
import http.cookiejar
import re
import sys
import json

BASE_URL = "https://student-marketplace-1dzk.onrender.com"

# Setup cookie handler and opener
cj = http.cookiejar.CookieJar()
opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cj))
# Add standard headers to mimic a real browser
opener.addheaders = [
    ('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')
]

def make_request(url, data=None, method='GET'):
    if data is not None:
        if isinstance(data, dict):
            # For file upload multipart form data, if needed.
            # But since image is optional, we can just use normal urlencoded for POST!
            encoded_data = urllib.parse.urlencode(data).encode('utf-8')
        else:
            encoded_data = data
        req = urllib.request.Request(url, data=encoded_data, method=method)
    else:
        req = urllib.request.Request(url, method=method)
    
    try:
        with opener.open(req) as response:
            html = response.read().decode('utf-8')
            info = response.info()
            final_url = response.geturl()
            return response.status, html, final_url, info
    except urllib.error.HTTPError as e:
        html = e.read().decode('utf-8') if e.fp else ""
        return e.code, html, url, None
    except Exception as e:
        return 500, str(e), url, None

def run_tests():
    results = {}
    
    print("Step 1: Check live production site status...")
    status, html, final_url, _ = make_request(BASE_URL)
    results['live_site'] = "Working" if status == 200 else f"Not Working (Status: {status})"
    print(f"Live site status: {results['live_site']}")
    
    if status != 200:
        print(f"Error HTML: {html[:500]}")
        return results

    # Generate a unique username to avoid conflicts
    import random
    suffix = random.randint(1000, 9999)
    test_username = f"tester_{suffix}"
    test_email = f"tester_{suffix}@example.com"
    test_password = "Password123"
    test_fullname = f"Test User {suffix}"
    test_phone = "9876543210"
    test_college_id = "202412345678"

    print(f"\nStep 2: Testing User Registration for: {test_username}...")
    reg_data = {
        'username': test_username,
        'email': test_email,
        'password': test_password,
        'full_name': test_fullname,
        'phone': test_phone,
        'college_id': test_college_id
    }
    status, html, final_url, _ = make_request(f"{BASE_URL}/register", reg_data, 'POST')
    # If successful, it redirects to login or shows flash message.
    print(f"Registration status code: {status}, Final URL: {final_url}")
    results['registration'] = "Success" if "login" in final_url or "successful" in html.lower() else "Failed"
    print(f"Registration status: {results['registration']}")

    print(f"\nStep 3: Testing User Login for: {test_username}...")
    login_data = {
        'username': test_username,
        'password': test_password
    }
    status, html, final_url, _ = make_request(f"{BASE_URL}/login", login_data, 'POST')
    print(f"Login status code: {status}, Final URL: {final_url}")
    # Verify that the session is persisted and dashboard loads
    results['user_login'] = "Success" if "dashboard" in final_url or "welcome" in html.lower() or "my products" in html.lower() else "Failed"
    print(f"User login status: {results['user_login']}")

    product_id = None
    if results['user_login'] == "Success":
        print("\nStep 4: Testing Database Read/Write & Session Persistence via Product Creation...")
        # Since multipart forms are tricky in raw urllib without external libs,
        # we can build a simple multipart request manually or see if URL-encoded works.
        # Wait, the Flask route uses request.form.get, meaning standard form encoding (application/x-www-form-urlencoded)
        # works for everything EXCEPT the file itself, and request.files.get('image') will just return None, which is fine!
        prod_data = {
            'name': f"Verify Product {suffix}",
            'description': "Autogenerated validation product description.",
            'price': "49.99",
            'category': "Textbooks",
            'stock': "10"
        }
        status, html, final_url, _ = make_request(f"{BASE_URL}/product/upload", prod_data, 'POST')
        print(f"Product creation status code: {status}, Final URL: {final_url}")
        
        # Verify if product exists on the user's dashboard
        status, html, final_url, _ = make_request(f"{BASE_URL}/dashboard")
        # Find the product ID from the edit links
        match = re.search(r'/product/edit/(\d+)', html)
        if match:
            product_id = match.group(1)
            results['product_creation'] = f"Success (Product ID: {product_id})"
            print(f"Product creation: {results['product_creation']}")
            results['db_read_write'] = "Success"
        else:
            results['product_creation'] = "Failed (Could not find created product on dashboard)"
            print(f"Product creation: {results['product_creation']}")
            results['db_read_write'] = "Failed (Write or Read error)"
            
        if product_id:
            print(f"\nStep 5: Testing Product Editing for ID {product_id}...")
            edit_data = {
                'name': f"Verify Product {suffix} Edited",
                'description': "Edited autogenerated validation product description.",
                'price': "59.99",
                'category': "Textbooks"
            }
            status, html, final_url, _ = make_request(f"{BASE_URL}/product/edit/{product_id}", edit_data, 'POST')
            print(f"Product editing status code: {status}, Final URL: {final_url}")
            
            # Check dashboard again to verify edit
            status, html, final_url, _ = make_request(f"{BASE_URL}/dashboard")
            results['product_editing'] = "Success" if f"Verify Product {suffix} Edited" in html else "Failed"
            print(f"Product editing: {results['product_editing']}")
            
            print(f"\nStep 6: Testing Product Deletion for ID {product_id}...")
            # Deletion is a POST request to /product/delete/<id>
            status, html, final_url, _ = make_request(f"{BASE_URL}/product/delete/{product_id}", {}, 'POST')
            print(f"Product deletion status code: {status}, Final URL: {final_url}")
            
            # Check dashboard again to verify deletion
            status, html, final_url, _ = make_request(f"{BASE_URL}/dashboard")
            results['product_deletion'] = "Success" if f"Verify Product {suffix}" not in html else "Failed"
            print(f"Product deletion: {results['product_deletion']}")
        else:
            results['product_editing'] = "Skipped"
            results['product_deletion'] = "Skipped"
            
        print("\nStep 7: Testing Logout...")
        status, html, final_url, _ = make_request(f"{BASE_URL}/logout")
        results['logout'] = "Success" if "logged out" in html.lower() or "login" in final_url else "Failed"
        print(f"Logout status: {results['logout']}")
    else:
        results['product_creation'] = "Skipped"
        results['db_read_write'] = "Skipped"
        results['product_editing'] = "Skipped"
        results['product_deletion'] = "Skipped"
        results['logout'] = "Skipped"

    print("\nStep 8: Testing Admin Login...")
    # Seed admin to ensure it exists or verify it
    admin_user = "Aditya"
    admin_pass = "Aditya@2103"
    
    # Try logging in directly
    admin_login_data = {
        'username': admin_user,
        'password': admin_pass
    }
    cj.clear() # clear previous user session cookies
    status, html, final_url, _ = make_request(f"{BASE_URL}/admin/login", admin_login_data, 'POST')
    print(f"Admin login status code: {status}, Final URL: {final_url}")
    
    results['admin_login'] = "Success" if "admin/dashboard" in final_url or "statistics" in html.lower() or "pending products" in html.lower() else "Failed"
    print(f"Admin login status: {results['admin_login']}")
    
    if results['admin_login'] == "Success":
        results['admin_dashboard'] = "Success"
        results['session_persistence'] = "Success"
    else:
        results['admin_dashboard'] = "Failed"
        results['session_persistence'] = "Failed"

    return results

if __name__ == "__main__":
    res = run_tests()
    print("\n" + "="*40)
    print("FINAL TEST RESULTS JSON:")
    print(json.dumps(res, indent=2))
    print("="*40)
